### ISSUE TITLE
Powering dropper that pointing any inventory that using this lib will killing the world

### ISSUE THREAD

**Issue by panbanann** [AlexIIL/LibBlockAttributes#40] opened 2021-02-19 10:13 UTC
As in title simple Redstone contraption with dropper powered by button, pointing any inventory which is using your lib, will crash the single-player game and server.

[https://pastebin.com/TuwkxbGn](https://pastebin.com/TuwkxbGn)

**Comment by AlexIIL** [comment] 2021-02-19 20:25
I think this is a duplicate of #34, and so can be fixed by manually updating LBA to [0.8.5](https://alexiil.uk/maven/alexiil/mc/lib/libblockattributes-all/0.8.5/libblockattributes-all-0.8.5.jar)?

**Comment by panbanann** [comment] 2021-02-19 20:41
It works! Thank you! sorry for the duplicate and problem.

**Comment by AlexIIL** [comment] 2021-02-19 22:05
OK :)

**Closed as completed by AlexIIL** 2021-02-19 22:05 UTC
Labels: type:bug, version: out of date
